name: Check external links

on: [push, pull_request]

jobs:
  check-links-external:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - run: npm ci
      - run: npm run bootstrap
      - run: npm run test:links:external
