name: Check links

on: [push, pull_request]

jobs:
  check-links:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: google/wireit@setup-github-actions-caching/v1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - run: npm ci
      - run: npm run test:links
