name: Check internal links

on: [push, pull_request]

jobs:
  check-links-internal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - run: npm ci
      - run: npm run bootstrap
      - run: npm run build
      - run: npm run test:links:redirects
      - run: npm run test:links:internal
