name: Preview URL Comment

on:
  pull_request:
    # x
    types: [opened, synchronize]

jobs:
  preview-url-comment:
    runs-on: ubuntu-latest

    steps:
      # https://stackoverflow.com/a/59819441
      - name: Generate URL
        id: gen-url
        run: echo "::set-output name=url::https://pr${{ github.event.number }}-$(echo $GITHUB_SHA | cut -c1-8)---lit-dev-bvxw3ycs6q-uw.a.run.app/"

      # https://github.com/peter-evans/find-comment
      - name: Find existing comment
        uses: peter-evans/find-comment@v1
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: A preview of this PR will be available

      # https://github.com/peter-evans/create-or-update-comment
      - name: Create comment (if new)
        if: ${{ steps.find-comment.outputs.comment-id == 0 }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            A preview of this PR will be available at the URL(s) below.
            This comment will be updated on each push.
            Each build usually takes around 7 minutes.

            ${{ steps.gen-url.outputs.url }}
          reactions: eyes

      # https://github.com/peter-evans/create-or-update-comment
      - name: Update comment (if existing)
        if: ${{ steps.find-comment.outputs.comment-id != 0 }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: append
          body: ${{ steps.gen-url.outputs.url }}
