name: Unit tests

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - run: npm ci
      - run: npm run bootstrap
      - run: npm run build
      - run: npm run test:unit
